### PR TITLE
Improving on HttpAssetLoader

### PR DESCRIPTION
**Pull request by le-vlad**
This PR adds the following:
- Fixes bug when using HttpAssetLoader for Cyrillic translations.
- Allows downloading individual translations from the remote host. Similar to the default asset loader
- Adds a small explanation on how to deal with HttpAssetLoader

### CODE REVIEW

**Review by aissat — APPROVED** [review]

**Review by bw-flagship — APPROVED** [review]

**Comment by bw-flagship** [comment]
@le-vlad approval is ready, we can merge if you resolve the conflicts :)

**Comment by le-vlad** [comment]
Hey @bw-flagship 
It's been a while 😄 , but thanks for approving. I'm going to resolve the conflicts today and merge the PR.
Does that sound ok?

**Comment by bw-flagship** [comment]
> Hey @bw-flagship It's been a while 😄 , but thanks for approving. I'm going to resolve the conflicts today and merge the PR. Does that sound ok?

:D Yes, sorry for the late review. Sounds great!

**Comment by le-vlad** [comment]
@bw-flagship Hey! Conflicts were resolved. But we still waiting for the review from @Overman775

**Comment by bw-flagship** [comment]
I think we don't need the review from @Overman775 specifically, so let's merge. He still can intervene later if he reviews it :)

**Pull request merged**
