### PR TITLE
feature/smart-network-loader

### LINKED ISSUE #30: AssetOrNetworkAssetLoader
I want to solve this issue please..... 

> this library can be support getting locale from network when its available?
> 
> it seems this class don't work correctly and i get some error. [reference ](https://github.com/aissat/easy_localization/issues/38)
> 
> ```dart
> final String assetsLocalePath = 'assets/langs/';
>     runApp(EasyLocalization(
>       path: assetsLocalePath,
>       useOnlyLangCode: true,
>       child: MyApp(),
>       assetLoader: AssetOrNetworkAssetLoader(
>           assetsPath: assetsLocalePath,
>           localCacheDuration: Duration(days: 1), // how long the localizations file should be kept
>           localeUrl: (String localeName) =>  'http://example.com/$localeName'), // the URL for the remote locale file
>       supportedLocales:
>           supportedLocales.map((locale) => Locale(locale)).toList(),
> ```
> 
> The loader:
> 
> ```dart
> import 'dart:async';
> import 'dart:convert';
> import 'dart:io';
> 
> import 'package:connectivity/connectivity.dart';
> import 'package:easy_localization/easy_localization.dart';
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> import 'package:http/http.dart' as http;
> import 'package:path_provider/path_provider.dart';
> 
> const defaultTimeout = Duration(seconds: 1);
> 
> class AssetOrNetworkAssetLoader extends AssetLoader {
>   /// The local URL method which accepts a [localeName] and returns the full distant
>   /// localUrl
>   final Function localeUrl;
> 
>   /// The timeout for downloading the distant localization files
>   final Duration timeout;
> 
>   /// The default path for assets json files
>   final String assetsPath;
> 
>   /// The duration before refreshing local localizations files with distant ones
>   final Duration localCacheDuration;
> 
>   AssetOrNetworkAssetLoader(
>       {@required this.localeUrl,
>       this.timeout,
>       this.assetsPath,
>       this.localCacheDuration});
> 
>   @override
>   Future<Map<String, dynamic>> load(String localePath) async {
>     String string;
>     String localeName =
>         localePath.replaceFirst(assetsPath, '').replaceFirst('.json', '');
> 
>     // try loading local previously-saved localization file
>     if (await localTranslationExists(localeName)) {
>       string = await loadFromLocalFile(localeName);
>     }
> 
>     // no local or failed, check if internet and download the file
>     if (string == null && await isInternetConnectionAvailable()) {
>       string = await loadFromNetwork(localeName);
>     }
> 
>     // local cache duration was reached or no internet access but prefer local file to assets
>     if (string == null &&
>         await localTranslationExists(localeName, ignoreCacheDuration: true)) {
>       string = await loadFromLocalFile(localeName);
>     }
> 
>     // still nothing? Load from assets
>     if (string == null) {
>       string = await rootBundle.loadString(localePath);
>     }
> 
>     // then returns the json file
>     return json.decode(string);
>   }
> 
>   @override
>   Future<bool> localeExists(String localePath) => Future.value(true);
> 
>   Future<bool> isInternetConnectionAvailable() async {
>     ConnectivityResult connectivityResult =
>         await (Connectivity().checkConnectivity());
>     if (connectivityResult == ConnectivityResult.none) return false;
> 
>     final result = await Future.any([
>       InternetAddress.lookup('example.com'),
>       Future.delayed(timeout ?? defaultTimeout)
>     ]);
> 
>     if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
>       return true;
>     }
> 
>     return false;
>   }
> 
>   Future<String> loadFromNetwork(String localeName) async {
>     String url = localeUrl(localeName);
> 
>     try {
>       final response = await Future.any(
>           [http.get(url), Future.delayed(timeout ?? defaultTimeout)]);
> 
>       if (response != null && response.statusCode == 200) {
>         String content = response.body.toString();
> 
>         // check valid json before saving it
>         if (json.decode(content) != null) {
>           await saveTranslation(localeName, content);
>           return content;
>         }
>       }
>     } catch (e) {
>       print(e.toString());
>     }
> 
>     return null;
>   }
> 
>   Future<bool> localTranslationExists(String localeName,
>       {bool ignoreCacheDuration: false}) async {
>     File translationFile = await getFileForLocale(localeName);
> 
>     if (!await translationFile.exists()) {
>       return false;
>     }
> 
>     // don't check file's age
>     if (!ignoreCacheDuration) {
>       Duration difference =
>           DateTime.now().difference(await translationFile.lastModified());
> 
>       if (difference > (localCacheDuration ?? Duration(days: 1))) {
>         return false;
>       }
>     }
> 
>     return true;
>   }
> 
>   Future<String> loadFromLocalFile(String localeName) async {
>     return await (await getFileForLocale(localeName)).readAsString();
>   }
> 
>   Future<void> saveTranslation(String localeName, String content) async {
>     File file = await new File(await getFilenameForLocale(localeName))
>         .create(recursive: true);
>     return file.writeAsString(content);
>   }
> 
>   Future<String> get _localPath async {
>     final directory = await getTemporaryDirectory();
> 
>     return directory.path;
>   }
> 
>   Future<String> getFilenameForLocale(String localeName) async {
>     return "${await _localPath}/langs$localeName.json";
>   }
> 
>   Future<File> getFileForLocale(String localeName) async {
>     return File(await getFilenameForLocale(localeName));
>   }
> }
> ```

### PR DESCRIPTION
**Pull request by ariefwijaya**
## Purpose
- add new class `SmartNetworkAssetLoader` that able to fetch localization using online `.json` files from provided url.
- add configurable cache from network assets using `Duration(..)` class
- add Failover system to local assets when there is a failure when fetching the online `.json` and no caches stored
- inspired by and resolved #30 , #29 , #17 

## Types of changes
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## How to Test
Just use this class in the `assetLoader` attribute of `EasyLocalization` and configure it as you want
```
SmartNetworkAssetLoader(
          assetsPath: 'assets/translations',
          localCacheDuration: Duration(days: 1),
          localeUrl: (String localeName) => Constants.appLangUrl,
          timeout: Duration(seconds: 30)
)
```

## Environment
_Please define your environment to test this, you can choose multiple options.  Put an x in the boxes that apply_
- [X] Production
- [X] Development
- [X] Testing
- [X] Android
- [X] iOS

<details><summary> Attach your `flutter doctor -v` inside code block: </summary>
<p>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.3.1 21E258 darwin-arm, locale en-ID)
    • Flutter version 2.5.3 at /Users/ariefwijaya/fvm/versions/2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

 [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/ariefwijaya/Library/Android/sdk
    • Platform android-31, build-tools 33.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.3.1, Build version 13E500a
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2020.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

• No issues found!
```

</p>
</details>

## Expected Results
1. able to fetch localization data from provided url, otherwise get data from `assetsPath`
2. When the data has been fetched, it can be use even in offline because caches system

### CODE REVIEW

**Comment by Floul** [comment]
Really waiting for this feature, because we are planning to use a localization management system like Localizely or smth like this.

**Comment by ariefwijaya** [comment]
@aissat any update on this?

**Comment by Floul** [comment]
@ariefwijaya thank you. I see that it's merged now. How can I access it now? i can’t see it for easy_localization_loader 1.0.0.

**Comment by Floul** [comment]
Thank you @ariefwijaya . One more question. I need to pass a token with the http call to get a translation from Localizely. Is there any way to do it with this loader?

**Comment by ariefwijaya** [comment]
> Thank you @ariefwijaya . One more question. I need to pass a token with the http call to get a translation from Localizely. Is there any way to do it with this loader?

Not available yet, but we can add it. Please create an issue

**Comment by Floul** [comment]
> > Thank you @ariefwijaya . One more question. I need to pass a token with the http call to get a translation from Localizely. Is there any way to do it with this loader?
> 
> Not available yet, but we can add it. Please create an issue

https://github.com/aissat/easy_localization_loader/issues/37 done.

**Comment by PavieOlivier** [comment]
Hello,
As I can see , in your description, you are using .Json
We currently have CSVs,
Do we need to convert our CSVs to Json or is it ok to let out files be CSVs? 
(considering that our CSVs are kind. of hudge)

**Comment by ariefwijaya** [comment]
> Hello,
> As I can see , in your description, you are using .Json
> We currently have CSVs,
> Do we need to convert our CSVs to Json or is it ok to let out files be CSVs?
> (considering that our CSVs are kind. of hudge)

For now, we convert csv to json using javascript. Technically, it will download data from online spreadsheet, and convert it to json.

**Comment by PavieOlivier** [comment]
> For now, we convert csv to json using javascript. Technically, it will download data from online spreadsheet, and convert it to json.

ok ok, thanks :) 
I will try to make it work then

**Pull request merged**
