### PR TITLE
Added missing JsonAssetLoader implementation

### PR DESCRIPTION
**Pull request by mauriziopinotti**
Hi,

I just added the missing implementation of JsonAssetLoader and JsonSingleAssetLoader, freely inspired by YamlAssetLoader.

### CODE REVIEW

**Comment by Overman775** [comment]
@mauriziopinotti JsonAssetLoader implemented in easy_localization package

**Comment by Overman775** [comment]
https://github.com/aissat/easy_localization/blob/develop/lib/src/asset_loader.dart

**Comment by mauriziopinotti** [comment]
@Overman775 shouldn't it be [here](https://github.com/aissat/easy_localization_loader/blob/master/lib/src/json_asset_loader.dart) along with all others loaders?

**Comment by CodeDoctorDE** [comment]
Please merge it!

**Review by aissat — APPROVED** [review]

**Comment by mauriziopinotti** [comment]
@Overman775 I updated the pull request with latest code from master and added checks for null-safety to JsonAssetLoader

**Comment by mauriziopinotti** [comment]
@aissat @Overman775 ping

**Comment by aissat** [comment]
> @aissat @Overman775 ping

Hi bro sorry  I'll check it, I was very busy 
Thank you for your contribution 👍👍

**Pull request merged**
